before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

addons:
  firefox: "17.0"

language: python

python:
  - "3.3"

install: 
  - pip install -r requirements.txt

script: 
  - python manage.py test lists
